apiVersion: v1
kind: Service
metadata:
  name: register
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    # 节点暴露给外部的端口（范围必须为30000-32767）
    nodePort: 30001
  selector:
    app: register